### PR TITLE
removed lastname field in person

### PR DESCRIPTION
**Pull request by PiXHULA**

### CODE REVIEW

**Review by fazlizekiqi — COMMENTED** [review]
Great Job!

**Review by violofsson — APPROVED** [review]

**Comment by PiXHULA** [comment]
What a wonderful codesnip

**Review by fazlizekiqi — APPROVED** [review]

**Comment by Kidboo10** [comment]
nice

**Review by fazlizekiqi — APPROVED** [review]

**Review by Kidboo10 — APPROVED** [review]
ELLLER hUUUR

**Pull request merged**
